### ISSUE TITLE
request:alignment flex layout icon space-between,space-around

### ISSUE THREAD

**Issue by joebnb** [radix-ui/icons#46]
beautiful web sites and categoryed icons. pls extend flex layout icon will better for current front dev sence(most fontend developer are used it).

there missing space-between,space-around in alignment.

https://developer.mozilla.org/de/docs/Web/CSS/justify-content
https://developer.mozilla.org/de/docs/Web/CSS/align-items

**Comment by vladmoroz** [comment]
Thanks for the request! We are adding `space-between` icons in 4.0.0, see #61

No plans for `space-around` yet since it's debatable whether it is possible to create it in a clean, legible design at 15x15. Also, it's not a hugely popular way to do flex layouts anyway. Feel free to do a PR with a design if you have any ideas.
